export default {
  GET_ALL_DATA: 'GET_ALL_DATA',
  GET_ALL_DATA_SUCCESS: 'GET_ALL_DATA_SUCCESS',
  SAVE_DATA: 'SAVE_DATA',
  SAVE_DATA_SUCCESS: 'SAVE_DATA_SUCCESS',
  SET_TODO_COMPLETED: 'SET_TODO_COMPLETED',
  DELETE_DATA: 'DELETE_DATA',
  TOGGLE_NOTIFICATIONS: 'TOGGLE_NOTIFICATIONS',
  UPDATE_NOTIFICATION_NR: 'UPDATE_NOTIFICATION_NR',
  NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
};
